export const routes = {
  laoding: 'Loading',
  selectlang: 'SelectLang',
  intro: 'Intro',
  intro2: 'Intro2',
  goal: 'Goal',
  home: 'Home',
  auth: 'Auth',
  app: 'App',
  loader: 'Loading',
  test: 'Test',
  tests: 'Tests',
  vdos:'Vdos',
  vdolist: 'VdoList',
  couses: 'Courses', //alias of VdoList
  vdoGroup: 'VdoGroup',
  register: 'SignUp',
  confirm: 'ConfirmSignUp',
  login: 'SignIn',
  signin: 'SignIn',
  forget: 'ForgetPassword',
  password: 'ConfirmPassword',
  changePassword: 'ChangePassword',
  result: 'Result',
  profile: 'Profile',
  settings: 'Settings',
};